### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by droid-Q** [waylybaye/LoveBundle#4]
surge 下lovebundle报这个错误
`ss-tls stderr |  2017-11-03 01:50:44 ERROR: failed to handshake with 127.0.0.1: authentication error
 2017-11-03 01:50:44 [simple-obfs] ERROR: remote recv: Connection reset by peer`
可能的原因是什么？shadowrocket是正常的，配置我一再确认过是一样的。

**Comment by waylybaye** [comment]
应该还是配置的问题，这个是认证失败导致的

**Comment by droid-Q** [comment]
@waylybaye 弄不懂surge什么鬼，配置完全一样。。。
